version: "3.5"
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  reverse-proxy:
    image: nginx:1.19
    depends_on:
      - truora_api
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 81:81
  load-balancer:
    image: nginx:1.17.7
    depends_on:
      # Hostnames referenced in nginx.conf need to be available
      # before Nginx starts
      - zero1
      - zero2
      - zero3
      - alpha1
      - alpha2
      - alpha3
    ports:
      - 80:80
      - 8080:8080
      - 9080:9080
    volumes:
      - type: bind
        source: ./load-balancer/nginx.conf
        target: /etc/nginx/conf.d/dgraph.conf
        read_only: true
  truora_api:
    image: truora_api
    build:
      context: ./server/
    ports:
      - 3000:3000
    depends_on:
      - load-balancer
      - redis
    restart: on-failure
  alpha1:
    image: dgraph/dgraph:latest
    container_name: alpha1
    hostname: alpha1
    ports:
    - 8080
    - 9080
    command: dgraph alpha --whitelist 0.0.0.0/0 --my=alpha1:7080 --lru_mb=1024 --zero=zero1:5080 --logtostderr
      -v=2 --idx=1
  alpha2:
    image: dgraph/dgraph:latest
    container_name: alpha2
    hostname: alpha2
    depends_on:
    - alpha1
    labels:
      cluster: test
    ports:
    - 8080
    - 9080
    command: dgraph alpha --whitelist 0.0.0.0/0  --my=alpha2:7080 --lru_mb=1024 --zero=zero1:5080 --logtostderr
      -v=2 --idx=2
  alpha3:
    image: dgraph/dgraph:latest
    container_name: alpha3
    hostname: alpha3
    ports:
    - 8080
    - 9080
    command: dgraph alpha --whitelist 0.0.0.0/0 --my=alpha3:7080 --lru_mb=1024 --zero=zero1:5080 --logtostderr
      -v=2 --idx=3
  zero1:
    image: dgraph/dgraph:latest
    container_name: zero1
    hostname: zero1
    ports:
    - 5080
    - 6080
    command: dgraph zero --idx=1 --my=zero1:5080 --replicas=3 --logtostderr -v=2
      --bindall
  zero2:
    image: dgraph/dgraph:latest
    container_name: zero2
    hostname: zero2
    ports:
    - 5080
    - 6080
    command: dgraph zero --idx=2 --my=zero2:5080 --replicas=3 --logtostderr -v=2
      --peer=zero1:5080
  zero3:
    image: dgraph/dgraph:latest
    container_name: zero3
    hostname: zero3
    ports:
    - 5080
    - 6080
    command: dgraph zero --idx=3 --my=zero3:5080 --replicas=3 --logtostderr -v=2
      --peer=zero1:5080
volumes: {}
