version: '3.5'

services:

  #Proxies requests to internal app
  reverse-proxy:
    image: nginx:1.19
    container_name: reverse-proxy
    depends_on:
      - go-server
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 81:81

  #app
  go-server:
    image: go-server
    container_name: go-server
    build:
      context: ./server
    ports:
      - "3000"
    restart: on-failure